name: Ops tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ops-tests:
    name: Run ops tests on Node LTS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --recursive --silent

      - name: Run ops tests
        env:
          NODE_ENV: test
        run: pnpm -w -C ops test:ops
